name: Build Classic Virtio drivers

on:
  push:
    # Build for non-release tags only
    branches:
      - "**"
    tags:
      - "!v*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Classic Virtio drivers build
    container:
      image: ghcr.io/autc04/retro68
      env:
        INTERFACES: universal
        INTERFACESFILE: "${{ secrets.INTERFACESFILE }}"
    steps:
      - name: Checkout Classic Virtio drivers
        uses: actions/checkout@v2

      - name: Configure Interfaces
        run: /Retro68-build/bin/docker-entrypoint.sh

      - name: Build drivers
        run: make

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: classicvirtio-drivers-latest
          path: |
            build/classic/declrom
            build/ndrv/ndrvloader

      - name: Prepare pre-release from artifacts
        uses: actions/download-artifact@v2
        with:
          name: classicvirtio-drivers-latest
          path: archive

      - name: Archive pre-release
        run: cd archive && zip -r ../classicvirtio-drivers-latest.zip .

      - name: Upload pre-release
        if: "${{ github.ref_name == 'main' }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
        run: |
          gh release create "latest" \
              --prerelease \
              --repo="$GITHUB_REPOSITORY" \
              --title="Development Build" \
              --generate-notes \
              classicvirtio-drivers-latest.zip
